id = "one-dark-vivid"
name = "One Dark Vivid"
description = "Zed - One Dark Vivid Theme, Ported from One Dark Pro"
version = "0.1.0"
schema_version = 1
authors = ["Manikandan B <xqsit94@gmail.com>"]
repository = "https://github.com/xqsit94/zed-one-dark-vivid"
